# how many distinct terms are in the sequence generated by a^b for 
# 2 <= a <= 100 and 2 <= b <= 100?

def num_distinct_int_powers(a_range: tuple[int, int], 
                            b_range: tuple[int, int]):
    """Number of distinct terms in the sequence generated by a^b.
    Args:
        a_range: tuple, lower and upper limit of base number
        b_range: tuple, lower and upper limit of power
    Return:
        int, number of distinct terms
        
    Usage examples:
    >>> num_distinct_int_powers(a_range=(2, 5), b_range=(2, 5))
    15
    >>> num_distinct_int_powers(a_range=(2, 3), b_range=(2, 3))
    4"""
    unique_num = set()

    for a in range(a_range[0], a_range[1] + 1):
        for b in range(b_range[0], b_range[1] + 1):
            unique_num.add(a ** b)

    return len(unique_num)

if __name__ == '__main__':
    import doctest
    doctest.testmod()

    print(num_distinct_int_powers(a_range=(2, 100), b_range=(2, 100)))